# Generated by Django 6.1 on 2026-08-13 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(choices=[('food', 'Room Service - Food & Drinks'), ('laundry', 'Laundry'), ('housekeeping', 'Housekeeping'), ('extra', 'Extras (Airport Pickup, Spa, Late Checkout, Wake-up Call)')], max_length=20)),
                ('details', models.TextField(help_text='Free text summary of the order, e.g. "2x Jollof Rice, 1x Towels"')),
                ('room_number', models.CharField(blank=True, max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_option', models.CharField(choices=[('charge_to_room', 'Charge to Room'), ('pay_instantly', 'Pay Instantly')], default='charge_to_room', max_length=20)),
                ('status', models.CharField(choices=[('new', 'New'), ('acknowledged', 'Acknowledged'), ('in_progress', 'In Progress'), ('ready', 'Ready / Done'), ('delivered', 'Delivered')], default='new', max_length=20)),
                ('placed_via', models.CharField(default='Guest Portal', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_orders', to='bookings.booking')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
