# Generated by Django 5.2.17 on 2026-08-19 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestportal', '0002_alter_serviceorder_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceorder',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
