# Generated by Django 6.1 on 2026-08-13 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('capacity_seated', models.PositiveIntegerField()),
                ('capacity_standing', models.PositiveIntegerField()),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='events/')),
                ('features', models.TextField(help_text='Comma separated, e.g. Stage, PA System, Projector')),
            ],
        ),
        migrations.CreateModel(
            name='EventInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_code', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('event_type', models.CharField(choices=[('wedding', 'Wedding'), ('conference', 'Conference / Business Meeting'), ('birthday', 'Birthday / Anniversary'), ('corporate', 'Corporate Retreat'), ('other', 'Other')], max_length=20)),
                ('preferred_date', models.DateField()),
                ('guest_count', models.PositiveIntegerField()),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New Inquiry'), ('quoted', 'Quote Sent'), ('confirmed', 'Confirmed'), ('closed', 'Closed')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event_space', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.eventspace')),
            ],
            options={
                'verbose_name_plural': 'Event inquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
