# Generated by Django 6.1 on 2026-08-13 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('category', models.CharField(choices=[('standard', 'Standard'), ('deluxe', 'Deluxe'), ('exclusive', 'Exclusive Suite'), ('presidential', 'Presidential Suite')], default='standard', max_length=20)),
                ('tagline', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField()),
                ('base_price', models.DecimalField(decimal_places=2, help_text='Price per night in NGN', max_digits=10)),
                ('capacity_adults', models.PositiveIntegerField(default=2)),
                ('capacity_children', models.PositiveIntegerField(default=1)),
                ('bed_type', models.CharField(default='1 King Bed', max_length=100)),
                ('size_sqm', models.PositiveIntegerField(default=28)),
                ('total_rooms', models.PositiveIntegerField(default=10)),
                ('amenities', models.TextField(help_text='Comma separated list, e.g. Free WiFi, Smart TV, Mini Bar')),
                ('cover_image', models.ImageField(upload_to='rooms/')),
                ('is_featured', models.BooleanField(default=False)),
                ('floor_range', models.CharField(blank=True, default='2nd - 4th Floor', max_length=50)),
            ],
            options={
                'ordering': ['base_price'],
            },
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='rooms/gallery/')),
                ('caption', models.CharField(blank=True, max_length=150)),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='rooms.roomtype')),
            ],
        ),
    ]
