# Generated by Django 6.1 on 2026-08-13 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('exterior', 'Exterior'), ('rooms', 'Rooms & Suites'), ('restaurant', 'Restaurant & Dining'), ('events', 'Events & Conference'), ('pool', 'Pool & Recreation'), ('spa', 'Spa & Wellness')], max_length=20)),
                ('image', models.ImageField(upload_to='gallery/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
