# Generated by Django 6.1 on 2026-08-13 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('category', models.CharField(choices=[('travel', 'Travel Tips'), ('local', 'Local Attractions'), ('hotel-news', 'Hotel News'), ('food', 'Food & Dining')], default='travel', max_length=20)),
                ('excerpt', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('cover_image', models.ImageField(upload_to='blog/')),
                ('author', models.CharField(default='Xceptional Place Team', max_length=100)),
                ('published_date', models.DateField()),
            ],
            options={
                'ordering': ['-published_date'],
            },
        ),
    ]
