# Generated by Django 6.1 on 2026-08-13 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('wellness', 'Wellness & Recreation'), ('business', 'Business & Events'), ('convenience', 'Convenience'), ('safety', 'Safety & Trust')], default='wellness', max_length=20)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='sparkles', help_text='lucide icon name', max_length=40)),
                ('image', models.ImageField(blank=True, null=True, upload_to='amenities/')),
                ('hours', models.CharField(blank=True, max_length=100)),
                ('is_highlighted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Amenities',
            },
        ),
    ]
