# Generated by Django 6.1 on 2026-08-13 11:05

import bookings.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddOn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('icon', models.CharField(default='sparkles', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_code', models.CharField(default=bookings.models.generate_reference, editable=False, max_length=20, unique=True)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('adults', models.PositiveIntegerField(default=1)),
                ('children', models.PositiveIntegerField(default=0)),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('whatsapp_opt_in', models.BooleanField(default=True)),
                ('special_requests', models.TextField(blank=True)),
                ('room_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('addon_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending Payment'), ('confirmed', 'Confirmed'), ('checked_in', 'Checked In'), ('checked_out', 'Checked Out'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('partial', 'Partial (Pay at Hotel)')], default='unpaid', max_length=20)),
                ('payment_method', models.CharField(default='Paystack', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('addons', models.ManyToManyField(blank=True, related_name='bookings', to='bookings.addon')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='rooms.roomtype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
